// Merges _raw/*_chunks.json + *_meta.json (translations/vocab) + *_enrich.json
// (furigana, grammar, examples, paragraphs) into novelData.ts. Fields are null
// when not yet generated; the UI degrades gracefully and fills on-demand.
import { readFileSync, writeFileSync, existsSync } from "fs";

const RAW = "/home/jack/french-shadowing/novels/_raw";
const OUT = "/home/jack/french-shadowing/novels/novelData.ts";

function load(file) { if (!existsSync(file)) return null; try { return JSON.parse(readFileSync(file, "utf-8")); } catch { return null; } }

function buildNovel(chunksFile, metaFile, enrichFile) {
  const data = load(`${RAW}/${chunksFile}`);
  const meta = load(`${RAW}/${metaFile}`) || {};
  const enrich = load(`${RAW}/${enrichFile}`) || {};
  const novel = data.novel;
  const days = data.chunks.map((c) => {
    const m = meta[String(c.day)] || {};
    const e = enrich[String(c.day)] || {};
    const isJp = novel.language === "japanese";
    // vocabulary: prefer enriched (has examples), else meta vocabulary
    let vocabulary = Array.isArray(e.vocabulary) && e.vocabulary.length ? e.vocabulary : (Array.isArray(m.vocabulary) ? m.vocabulary : null);
    // furigana (Japanese only) — array aligned 1:1 with paragraphs
    const furiganaParagraphs = isJp && Array.isArray(e.furiganaParagraphs) && e.furiganaParagraphs.length ? e.furiganaParagraphs : null;
    const paragraphs = Array.isArray(e.paragraphs) && e.paragraphs.length ? e.paragraphs : null;
    const grammar = Array.isArray(e.grammar) && e.grammar.length ? e.grammar : null;
    const keywords = vocabulary ? vocabulary.map((v) => v.word).filter(Boolean) : [];
    return {
      day: c.day,
      title: m.dayTitle || e.title || `Day ${c.day}`,
      text: c.text,
      paragraphs,
      translation: m.translation || null,
      vocabulary,
      grammar,
      furiganaParagraphs,
      keywords,
    };
  });
  const generated = days.filter((d) => d.translation).length;
  const enriched = days.filter((d) => d.grammar && d.grammar.length).length;
  return { novelOut: { id: novel.id, language: novel.language, title: novel.title, titleEn: novel.titleEn || novel.title_en || undefined, author: novel.author, theme: novel.theme, source: novel.source, blurb: novel.blurb, days }, generated, enriched, total: days.length };
}

const fr = buildNovel("fr_chunks.json", "fr_meta.json", "fr_enrich.json");
const jp = buildNovel("jp_chunks.json", "jp_meta.json", "jp_enrich.json");

const ts = `// AUTO-GENERATED by novels/build_data.mjs — do not edit by hand.
// Sourced from public-domain novels (see novel.source). Translations, furigana,
// grammar and examples are pre-generated where available; the UI fills the rest
// on demand (cached), so the page works even with partial data.

export interface VocabItem {
  word: string;
  phonetic: string;        // IPA (French) or romaji (Japanese)
  translation: string;
  example?: string;              // example sentence in the target language
  exampleTranslation?: string;   // English translation of the example
}
export interface GrammarPoint {
  point: string;          // the grammar pattern as it appears
  explanation: string;    // plain-English explanation for a self-learner
}
export interface NovelDay {
  day: number;
  title: string;
  text: string;                  // clean passage
  paragraphs: string[] | null;   // passage split into paragraphs (for formatting)
  translation: string | null;    // English translation
  vocabulary: VocabItem[] | null;
  grammar: GrammarPoint[] | null;
  furiganaParagraphs: string[] | null;   // Japanese only: per-paragraph text with 漢字[かんじ] markup
  keywords: string[];            // words to highlight in the passage
}
export interface Novel {
  id: string;
  language: 'french' | 'japanese';
  title: string;
  titleEn?: string;
  author: string;
  theme: string;
  source: string;
  blurb: string;
  days: NovelDay[];
}

export const NOVELS: Novel[] = [
${JSON.stringify(fr.novelOut, null, 2)},
${JSON.stringify(jp.novelOut, null, 2)}
];
`;

writeFileSync(OUT, ts);
console.log(`Wrote ${OUT}`);
console.log(`  FR: ${fr.generated}/${fr.total} translations, ${fr.enriched} enriched`);
console.log(`  JP: ${jp.generated}/${jp.total} translations, ${jp.enriched} enriched`);
